version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - tar -czvf target/ConsultoriasAssesorias-0.0.1.tar.gz appspec.yml --directory=target ConsultoriasAssesorias-0.0.1.jar
      - echo Build completed on `date`
artifacts:
  files:
    - target/ConsultoriasAssesorias-0.0.1.tar.gz